# Generated by Django 5.1.3 on 2025-02-01 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=15)),
                ('genre', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=3)),
                ('orderdate', models.DateField()),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xdinaryBooks.book')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xdinaryBooks.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewid', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('review_datetime', models.DateTimeField()),
                ('reviewtext', models.TextField()),
                ('reviewimage', models.ImageField(blank=True, null=True, upload_to='review_images/')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xdinaryBooks.book')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xdinaryBooks.customer')),
            ],
        ),
    ]
