# Generated by Django 5.1.3 on 2025-02-15 03:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xdinaryBooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bookid',
        ),
        migrations.AlterField(
            model_name='order',
            name='orderid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='order',
            name='bookid',
            field=models.ManyToManyField(to='xdinaryBooks.book'),
        ),
    ]
